# Assignment 1

1. Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
2. Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable
3. Split the vector into in 1 above three arrays by taking the first 15, follow by the next 20 and the remaining into another variable.
4. Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 (c). Using array of ones

In [1]:
import numpy as np

In [2]:
# 1. Generate an np array of (a) vector of lenght 50 
a = np.arange(1,51)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [3]:
# 1. Generate an np array of (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1
b = np.random.random((5,4))
b

array([[0.89925583, 0.22229878, 0.10191183, 0.7121536 ],
       [0.23026929, 0.31512997, 0.37001729, 0.87226766],
       [0.90960563, 0.47676884, 0.29713758, 0.28809243],
       [0.95611375, 0.24194855, 0.13207016, 0.12760796],
       [0.54295135, 0.46235282, 0.47100134, 0.56323785]])

In [4]:
# 2. Split the two dimension array in 1 above into three arrays taking the first two rows, 
# follow by the next two rows and put the remaining row in another variable
first_array, second_array, third_array = np.vsplit(b, [2,4])
print("The first array is\n", first_array, "\n")
print("The second array is\n", second_array, "\n")
print("The third array is\n", third_array, "\n")

The first array is
 [[0.89925583 0.22229878 0.10191183 0.7121536 ]
 [0.23026929 0.31512997 0.37001729 0.87226766]] 

The second array is
 [[0.90960563 0.47676884 0.29713758 0.28809243]
 [0.95611375 0.24194855 0.13207016 0.12760796]] 

The third array is
 [[0.54295135 0.46235282 0.47100134 0.56323785]] 



In [5]:
# 3. Split the vector in 1 above into three arrays by taking the first 15, follow by the next 20 
# and the remaining into another variable.
array_1, array_2, array_3 = np.split(a,(15, 35))
print(array_1, array_2, array_3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35] [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
# 4. Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 
# (c). Using array of ones

np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[15,16,17,18,20]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [15, 16, 17, 18, 20]])

In [7]:
# 4. Create a 4x5 array: (b). Using randomly generated value between 0 and 1 

np.random.random((4,5))

array([[0.53007066, 0.96110932, 0.49278796, 0.62145004, 0.05049521],
       [0.2480795 , 0.13406187, 0.66904737, 0.46390366, 0.74116593],
       [0.91572965, 0.97025797, 0.41519514, 0.20518979, 0.18361869],
       [0.73941599, 0.47139385, 0.09516621, 0.98162824, 0.90481748]])

In [8]:
# (c). Using array of ones
np.ones([4,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])